'use strict';
const hi = 'hello, World';
console.log(hi);
const $element = document.querySelector('h1');
console.dir($element);
const $element1 = document.querySelector('#explanation');
console.dir($element1);
const $element2 = document.querySelector('.hint');
console.dir($element2);
const $element3 = document.querySelectorAll('p');
console.dir($element3);
const $element4 = document.querySelectorAll('.example-link');
console.dir($element4);
