'use strict';
const fullName = 'Liam Nguyen';
const isCool = true;
const totalPets = 0;
const empty = null;
const nothing = undefined;
console.log('value of fullName: ', fullName);
console.log('value of isCool: ', isCool);
console.log('value of totalPets: ', totalPets);
console.log('value of empty: ', empty);
console.log('value of nothing: ', nothing);
console.log('typeof fullName: ', typeof fullName);
console.log('typeof isCool: ', typeof isCool);
console.log('typeof totalPets: ', typeof totalPets);
console.log('typeof empty: ', typeof empty);
console.log('typeof nothing: ', typeof nothing);
