'use strict';
const width = 5;
const len = 10;
const area = width * len;
console.log('value of area: ', area);
console.log('type of area: ', typeof area);
const bill = 200;
const payment = 1000;
const change = payment - bill;
console.log('value of change: ', change);
console.log('type of change: ', typeof change);
const quizzes = 90;
const midterm = 100;
const final = 40;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ', grade);
console.log('type of grade: ', typeof grade);
const firstName = 'Liam';
const lastName = ' Nguyen';
const fullName = firstName + lastName;
console.log('value of fullName: ', fullName);
console.log('type of fullName: ', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic', isAcidic);
console.log('type of isAcidic ', typeof isAcidic);
const headcount = 100;
const isSparta = headcount === 300;
console.log('value of isSparta', isSparta);
console.log('type of is Sparta', typeof isSparta);
const motto = fullName + ' is the GOAT';
console.log('value of motto ', motto);
console.log('type of motto ', typeof motto);
